export const POST_ASSIGNPERSONNEL = "POST_ASSIGNPERSONNEL";
export const GET_ASSIGNPERSONNELS = "GET_ASSIGNPERSONNELS";
export const GET_ASSIGNPERSONNEL = "GET_ASSIGNPERSONNEL";
export const GET_PERSONNELSCHEDULE = "GET_PERSONNELSCHEDULE";
