export const GET_EQUIPMENTS = "GET_EQUIPMENTS";
export const GET_EQUIPMENT = "GET_EQUIPMENT";
export const CREATE_EQUIPMENTS = "CREATE_EQUIPMENTS";
export const DELETE_EQUIPMENTS = "DELETE_EQUIPMENTS";
export const GET_COMPUTER = "GET_COMPUTER";
export const GET_ALLDESKTOP = "GET_ALLDESKTOP";
