export const GET_EQUIPMENTS = "GET_EQUIPMENTS";
export const GET_EQUIPMENT = "GET_EQUIPMENT";
export const CREATE_EQUIPMENTS = "CREATE_EQUIPMENTS";
export const DELETE_EQUIPMENTS = "DELETE_EQUIPMENTS";
export const GET_ALLDSLR = "GET_ALLDSLR";
export const GET_ALLLENSES = "GET_ALLLENSES";
export const GET_ALLTRIPOD = "GET_ALLTRIPOD";

// export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const PUT_ALLUPDATEIMC = "PUT_ALLUPDATEIMC";
