export const GET_EQUIPMENTS = "GET_EQUIPMENTS";
export const GET_EQUIPMENT = "GET_EQUIPMENT";
export const CREATE_EQUIPMENTS = "CREATE_EQUIPMENTS";
export const DELETE_EQUIPMENTS = "DELETE_EQUIPMENTS";
