export const GET_SCHEDULES = "GET_SCHEDULES";
export const GET_SCHEDULE = "GET_SCHEDULE";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const PUT_EQUIPMENTSCHEDULE = "PUT_EQUIPMENTSCHEDULE";
