export const GET_PERSONNELS = "GET_PERSONNELS";
export const GET_PERSONNEL = "GET_PERSONNEL";
export const CREATE_PERSONNEL = "CREATE_PERSONNEL";
export const DELETE_PERSONNEL = "DELETE_PERSONNEL";
export const POST_ASSIGNIMCPERSONNEL = "POST_ASSIGNIMCPERSONNEL";
