export const GET_RESERVATION = "GET_RESERVATION";
export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
