export const GET_EQUIPMENTS = "GET_EQUIPMENTS";
export const GET_EQUIPMENT = "GET_EQUIPMENT";
export const CREATE_EQUIPMENTS = "CREATE_EQUIPMENTS";
export const DELETE_EQUIPMENTS = "DELETE_EQUIPMENTS";
export const GET_ALLSPEAKER = "GET_ALLSPEAKER";
export const GET_ALLBLUETOOTHSPEAKER = "GET_ALLBLUETOOTHSPEAKER";
export const GET_ALLMICROPHONE = "GET_ALLMICROPHONE";
export const GET_ALLPROJECTOR = "GET_ALLPROJECTOR";
export const GET_ALLPROJECTORSCREEN = "GET_ALLPROJECTORSCREEN";
export const GET_ALLLIGHTS = "GET_ALLLIGHTS";

export const PUT_ALLUPDATEVPA = "PUT_ALLUPDATEVPA";
